=== flare-foundation/fassets/deployment/config/ftsov2-price-store-parameters.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "additionalProperties": false,
    "definitions": {
        "FtsoV2Feed": {
            "additionalProperties": false,
            "properties": {
                "category": {
                    "type": "number"
                },
                "feedDecimals": {
                    "type": "number"
                },
                "feedId": {
                    "type": "string"
                },
                "source": {
                    "enum": [
                        "fastUpdates",
                        "scaling"
                    ],
                    "type": "string"
                },
                "symbol": {
                    "type": "string"
                }
            },
            "required": [
                "feedDecimals",
                "feedId",
                "symbol"
            ],
            "type": "object"
        }
    },
    "properties": {
        "$schema": {
            "type": "string"
        },
        "contractName": {
            "type": "string"
        },
        "feeds": {
            "items": {
                "$ref": "#/definitions/FtsoV2Feed"
            },
            "type": "array"
        },
        "firstVotingRoundStartTs": {
            "type": "number"
        },
        "maxSpreadBIPS": {
            "type": "number"
        },
        "minTurnoutBIPS": {
            "type": "number"
        },
        "trustedProviders": {
            "items": {
                "type": "string"
            },
            "type": "array"
        },
        "trustedProvidersThreshold": {
            "type": "number"
        },
        "votingEpochDurationSeconds": {
            "type": "number"
        }
    },
    "required": [
        "contractName",
        "feeds",
        "firstVotingRoundStartTs",
        "maxSpreadBIPS",
        "minTurnoutBIPS",
        "trustedProviders",
        "trustedProvidersThreshold",
        "votingEpochDurationSeconds"
    ],
    "type": "object"
}

=== flare-foundation/fassets/deployment/config/coston/ftsov2.json
{
    "$schema": "../ftsov2-price-store-parameters.json",
    "contractName": "FtsoV2PriceStore",
    "firstVotingRoundStartTs": 1658429955,
    "votingEpochDurationSeconds": 90,
    "trustedProviders": ["0xaec76c9b8fa7e13699e7dffbf7abfae5e943f1c1"],
    "trustedProvidersThreshold": 1,
    "maxSpreadBIPS": 50,
    "minTurnoutBIPS": 5000,
    "feeds": [
        { "feedId": "SGB/USD", "symbol": "CFLR", "feedDecimals": 7 },
        { "feedId": "BTC/USD", "symbol": "testBTC", "feedDecimals": 2 },
        { "feedId": "XRP/USD", "symbol": "testXRP", "feedDecimals": 5 },
        { "feedId": "DOGE/USD", "symbol": "testDOGE", "feedDecimals": 5 },
        { "feedId": "ETH/USD", "symbol": "testETH", "feedDecimals": 3 },
        { "feedId": "USDC/USD", "symbol": "testUSDC", "feedDecimals": 5 },
        { "feedId": "USDT/USD", "symbol": "testUSDT", "feedDecimals": 5 },
        { "feedId": "USDX/USD", "symbol": "testUSDX", "feedDecimals": 5, "source": "fastUpdates", "category": 33 }
    ]
}

=== flare-foundation/fassets/deployment/config/songbird/ftsov2.json
{
    "$schema": "../ftsov2-price-store-parameters.json",
    "contractName": "FtsoV2PriceStore",
    "firstVotingRoundStartTs": 1658429955,
    "votingEpochDurationSeconds": 90,
    "trustedProviders": [
        "0xFA55A150c926F43de6165A2062Ced1c179260f55",
        "0xF750178B0155c651B4FFf490cE01D0736F1b54C6",
        "0x96b83D3F73E44c9A96388CF1D116595551dAeB5A"
    ],
    "trustedProvidersThreshold": 2,
    "maxSpreadBIPS": 100,
    "minTurnoutBIPS": 5000,
    "feeds": [
        { "feedId": "SGB/USD", "symbol": "SGB", "feedDecimals": 7 },
        { "feedId": "USDX/USD", "symbol": "USDX", "feedDecimals": 5 },
        { "feedId": "XRP/USD", "symbol": "XRP", "feedDecimals": 5 },
        { "feedId": "DOGE/USD", "symbol": "DOGE", "feedDecimals": 5 },
        { "feedId": "BTC/USD", "symbol": "BTC", "feedDecimals": 2 }
    ]
}

=== flare-foundation/fassets/deployment/config/coston2-qa/ftsov2.json
{
    "$schema": "../ftsov2-price-store-parameters.json",
    "contractName": "FtsoV2PriceStore",
    "firstVotingRoundStartTs": 1658430000,
    "votingEpochDurationSeconds": 90,
    "trustedProviders": ["0xaec76c9b8fa7e13699e7dffbf7abfae5e943f1c1"],
    "trustedProvidersThreshold": 1,
    "maxSpreadBIPS": 50,
    "minTurnoutBIPS": 5000,
    "feeds": [
        { "feedId": "FLR/USD", "symbol": "C2FLR", "feedDecimals": 6 },
        { "feedId": "BTC/USD", "symbol": "testBTC", "feedDecimals": 2 },
        { "feedId": "XRP/USD", "symbol": "testXRP", "feedDecimals": 5 },
        { "feedId": "DOGE/USD", "symbol": "testDOGE", "feedDecimals": 5 },
        { "feedId": "ETH/USD", "symbol": "testETH", "feedDecimals": 3 },
        { "feedId": "USDC/USD", "symbol": "testUSDC", "feedDecimals": 5 },
        { "feedId": "USDT/USD", "symbol": "testUSDT", "feedDecimals": 5 }
    ]
}

=== flare-foundation/fassets/deployment/config/flare/ftsov2.json
{
    "$schema": "../ftsov2-price-store-parameters.json",
    "contractName": "FtsoV2PriceStore",
    "firstVotingRoundStartTs": 1658430000,
    "votingEpochDurationSeconds": 90,
    "trustedProviders": [
        "0xf750071F7bFD781431dcC2f0c28D9F500A063eff",
        "0x4033582ab84e24752Bf633391D7Fbef2ef4cFd11",
        "0xC1699acb7D6E0553FbA6a03d8A622b57955cfA1B"
    ],
    "trustedProvidersThreshold": 2,
    "maxSpreadBIPS": 100,
    "minTurnoutBIPS": 5000,
    "feeds": [
        { "feedId": "FLR/USD", "symbol": "FLR", "feedDecimals": 6 },
        { "feedId": "BTC/USD", "symbol": "BTC", "feedDecimals": 2 },
        { "feedId": "XRP/USD", "symbol": "XRP", "feedDecimals": 5 },
        { "feedId": "DOGE/USD", "symbol": "DOGE", "feedDecimals": 5 },
        { "feedId": "ETH/USD", "symbol": "ETH", "feedDecimals": 3 },
        { "feedId": "USDC/USD", "symbol": "USDC", "feedDecimals": 5 },
        { "feedId": "USDT/USD", "symbol": "USDT", "feedDecimals": 5 }
    ]
}
